### ISSUE TITLE
Typo in docs.html 

### ISSUE THREAD

**Issue by strassburger** [yanosz/node-config#3]
Tried to study.
First hint:
Typo in docs.html line 658: "https://github.com/node-config"
Think that link should be:
"https://kbu.freifunk.net/files/node-config/doc/" 
Same tipo in the mail of <wlanware@freifunk.net>:

**Comment by yanosz** [comment]
Thanks, fixed in 3d8858677932967dafa9560d29a6eba43e5df48b
